name: Security Scan with Trivy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

permissions:
  contents: read
  security-events: write

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in filesystem mode
        uses: aquasecurity/trivy-action@b3dafe507ffa004210975439a1e6156b8ebb3f50
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          severity: 'CRITICAL,HIGH'

      - name: Build an image from Dockerfile
        run: |
          docker build -t my-python-app:${{ github.sha }} .
          
      - name: Run Trivy vulnerability scanner in image mode
        uses: aquasecurity/trivy-action@b3dafe507ffa004210975439a1e6156b8ebb3f50
        with:
          image-ref: 'my-python-app:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'
          
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
